name: Python application test

on:
  push:
    branches:
      - main  # Ensures the workflow runs on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Sets up Python version 3.8, adjust as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest or any other dependencies you need

    - name: Run pytest
      run: |
        pytest  # Command to run your tests
